### ISSUE TITLE
svg logo outdated

### ISSUE THREAD

**Issue by ndalliard** [spesmilo/electrum-web#5]
Can someone provide me with the new svg version of the electrum icon?

I found the [png version](https://github.com/spesmilo/electrum-web/blob/master/logo/electrum_logo.png). But the [svg version](https://github.com/spesmilo/electrum-web/blob/master/logo/electrum_logo.svg) seems outdated.

**Comment by rdymac** [comment]
Hello @ndalliard. Here you can find the logo and also some icons from a few years ago: https://www.dropbox.com/sh/f6p1lhq7oteq41v/AABdR3iw2-2_9kP4kn9LlkBka 

Unfortunately, I don't have final designs in SVG form that you could use right away. There are .EPS files, .PSD, .sketch design files that you could use to create the SVG versions from and make public here for anyone to use.

ThomasV (@ecdsa) has approved making them public through IRC.

**Comment by ndalliard** [comment]
Thanks @rdymac for the files.

I am running on OpenBSD, I don't have Photoshop or Sketch to generate the SVG. I used an online tool to do so. And got the SVG icon with a file size of `18.8K`. Not sure if with Photoshop or Sketch I could get a smaller file. Maybe someone could try.

I am looking just for the icon (see [here](https://github.com/spesmilo/electrum-web/blob/master/logo/electrum_logo.png)).

**Comment by JeremyRand** [comment]
@rdymac Mind clarifying the license on those files?  Right now I don't see any license, which in most jurisdictions is equivalent to "all rights reserved", i.e. they're probably not legal to use.

**Comment by ndalliard** [comment]
I am using the icon on my site to promote Electrum. I guess I should be fine using it.

**Comment by JeremyRand** [comment]
> I am using the icon on my site to promote Electrum. I guess I should be fine using it.

@ndalliard That's only relevant to the question of "Am I likely to be sued?", not my question of "Under what terms can I be legally certain that I will not lose a lawsuit if someone sues me?"  :)

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/commit/dfc0f896b7f8073710d35b0012018d9fe50c80e4

https://raw.githubusercontent.com/spesmilo/electrum/f815f8eb30d9d9cb9db151c4347918ca8cfec409/electrum/gui/icons/electrum_darkblue.svg
https://raw.githubusercontent.com/spesmilo/electrum/f815f8eb30d9d9cb9db151c4347918ca8cfec409/electrum/gui/icons/electrum_lightblue.svg

These have file sizes around 8 KB.
They are in the main repo, so MIT license of course.

**Comment by ndalliard** [comment]
Thanks!
