### ISSUE TITLE
Link to privacy policy is broken

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum-web#58]
Some links to pages formerly loaded by javascript have been broken by #20: 
For example, https://electrum.org/#privacy (required by Google Play) is no longer reachable.

**Comment by SomberNight** [comment]
Indeed.

- We can either manually inline `panel-privacy.html` into `index.html.template`,
- or if you think it's cleaner to keep it a separate file, we can use the templating to have the `make_download` script dynamically inline it, just like for the download page.

**Comment by ecdsa** [comment]
added in a17424d5f1e9954f40f02011f8abd1853cde1ccf
